FROM node:alpine

WORKDIR '/app'

COPY package.json .

run apk --no-cache add --virtual native-deps \
  g++ gcc libgcc libstdc++ linux-headers make python && \
  npm install --quiet node-gyp -g &&\
  npm install --quiet && \
  apk del native-deps

RUN npm install

COPY . .

CMD ["npm", "run", "start"]